version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/health2.0-backstage-pre
permissions:
   - object: /var/www/html/health2.0-backstage-pre
     pattern: "**"
     owner: ec2-user
     group: ec2-user
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/remove.sh
      runas: root
    - location: scripts/startnginx.sh
      runas: root
   AfterInstall:
    - location: scripts/restartnginx.sh
      runas: root
    - location: scripts/install_npm.sh
      runas: ec2-user
