<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Cache;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withoutEvents();

        Cache::flush();

        ini_set('memory_limit', '512M');

        config(['database.connections.mysql_tvbs_old.is_sync' => false]);
    }
}
